### ISSUE TITLE
Consider not building the docs for the nightlies

### ISSUE THREAD

**Issue by japaric** [japaric/ruststrap#23]
This would greatly reduce build time, and the size of the nightlies; but I need to consider the impact on users.

So I need to ask the question: how useful/vital are the installed docs when developing on ARM devices?

When developing in amd64/arm I usually use the [hosted documentation](http://doc.rust-lang.org/std/) (or just browse through the source using my editor). So I'd be in favor of removing the docs from the nightlies.

I'll like to hear other people's opinion.

(Probably it's too early to ask, since it's been only a few days since I've started shipping the final form (RPi compatible) of the nightlies, so take your time to answer!)

cc @Novacha @shavounet

For the record building + uploading the nightlies takes:
- with docs: 3h 21m 59s
- without docs: 3h 9m 7s

**Comment by Novacha** [comment]
I use the online docs right now even though rustup installs them to my computer, so I wouldn't have a need rust docs to be on the ARM device. I also assume that the documentation would be exactly the same as the documentation generated by the rust linux buildbot and uploaded to the rust doc site, so it would superfluous to build them again. 

I'd say that it's probably not worth the extra build time and size.

**Comment by japaric** [comment]
Thanks for the input @Novacha! And yes, the docs should match since the nightlies are built from the same commit hash.

As an experiment, I'm building the next rust nightly without docs to get an idea of the reduction of build time/tarball size.

**Comment by StephanvanSchaik** [comment]
On Gentoo, ebuilds have a doc USE-flag for this, optionally allowing you to install the documentation in conjunction with the software. However, most users turn this off on a system-wide level, to save disk space (lots of it, imagine having this enabled for every common package, and having a beast like `texlive` installed) and because all the documentation is usually online somewhere. I am one of those users, as my Chromebooks only have 16 GiB or 32 GiB of space in total. I do have some ARM devices with a 120 GiB SSD attached to them via SATA, but I don't use those often, and still wouldn't populate it with documentation. Nevertheless, if I really wanted to, I could just enable the USE-flag and build it myself, which means there is no need for me to have documentation preshipped with the binaries.

To me offline documentation is only useful in situations where you have no internet connection, or a poor one. However, if there are people who want it, and it takes a lot of time to build, then it might be worth it to build it every ten releases or so.

**Comment by japaric** [comment]
Bah, `--disable-docs` only shaves 12 mins (6%) off the build time, and reduces the tarball size by 33 MB (25%).

I thought the win in build time was way bigger than this. At this point, I don't mind building the docs for every nightly. I guess the question is now whether you mind the extra bandwidth required to download a nightly with docs?

**Comment by japaric** [comment]
I'll continue to bundle the docs with the nightlies to be consistent with the official nightlies.

Thanks everyone for the input!
